default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  # password: <%= ENV.fetch("MYSQL_PASSWORD", "password") %>
  # host: <%= ENV.fetch("MYSQL_HOST", "db") %>
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: NW_SECURITY_development

test:
  <<: *default
  database: NW_SECURITY_test

production:
  <<: *default
  database: NW_SECURITY_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
